FROM php:8.4-fpm-alpine AS builder

RUN apk add --no-cache \
    autoconf \
    g++ \
    make \
    linux-headers

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN set -ex && \
    arch="$(uname -m)" && \
    if [ "$arch" = "aarch64" ] || [ "$arch" = "armv8l" ]; then \
        install-php-extensions bcmath gd mysqli pdo_mysql opcache pcntl redis swoole yaml zip; \
    else \
        install-php-extensions bcmath gd ioncube_loader mysqli pdo_mysql opcache pcntl redis swoole yaml zip; \
    fi && \
    rm -rf /var/cache/apk/* /etc/apk/cache/* /tmp/* /var/tmp/* /usr/local/lib/php/doc/* /root/.composer/cache /usr/local/bin/install-php-extensions

FROM php:8.4-fpm-alpine

ADD --chmod=0755 https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=builder /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/

RUN apk add --no-cache openrc \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel \
    && sed -i 's/^#rc_sys=".*"/rc_sys="docker"/' /etc/rc.conf || true \
    && echo "upload_max_filesize=1024M" > /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size=1024M" > /usr/local/etc/php/conf.d/post.ini \
    && echo "memory_limit=512M" > /usr/local/etc/php/conf.d/memory.ini \
    && echo "max_execution_time=1200" > /usr/local/etc/php/conf.d/max_execution_time.ini \
    && echo "max_input_time=600" > /usr/local/etc/php/conf.d/max_input_time.ini \
    && echo "max_input_vars=10000" > /usr/local/etc/php/conf.d/max_input_vars.ini \
    && rm -rf /var/cache/apk/* /etc/apk/cache/* /tmp/* /var/tmp/* /usr/local/lib/php/doc/* /root/.composer/cache

WORKDIR /var/www
COPY --chmod=0755 docker-entrypoint /usr/bin/

ENTRYPOINT ["docker-entrypoint"]
