FROM php:8.5-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
ADD --chmod=0755 https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

RUN apk add --no-cache openrc && \
    mkdir -p /run/openrc && \
    touch /run/openrc/softlevel && \
    sed -i 's/^#rc_sys=".*"/rc_sys="docker"/' /etc/rc.conf || true && \
    install-php-extensions bcmath gd mysqli pdo_mysql opcache pcntl redis swoole yaml zip && \
    arch="$(uname -m)"; \
    if [ "$arch" = "aarch64" ] || [ "$arch" = "armv8l" ]; then \
        IONCUBE_URL="https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_aarch64.tar.gz"; \
    else \
        IONCUBE_URL="https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz"; \
    fi && \
    wget -O /tmp/ioncube.tar.gz $IONCUBE_URL && \
    tar -xzf /tmp/ioncube.tar.gz -C /tmp && \
    PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;") && \
    EXTENSION_DIR=$(php -r "echo ini_get('extension_dir');") && \
    cp /tmp/ioncube/ioncube_loader_lin_${PHP_VERSION}.so $EXTENSION_DIR/ioncube.so && \
    echo "zend_extension=ioncube.so" > /usr/local/etc/php/conf.d/docker-php-ext-ioncube.ini && \
    echo "upload_max_filesize=1024M" > /usr/local/etc/php/conf.d/uploads.ini && \
    echo "post_max_size=1024M" > /usr/local/etc/php/conf.d/post.ini && \
    echo "memory_limit=512M" > /usr/local/etc/php/conf.d/memory.ini && \
    echo "max_execution_time=1200" > /usr/local/etc/php/conf.d/max_execution_time.ini && \
    echo "max_input_time=600" > /usr/local/etc/php/conf.d/max_input_time.ini && \
    echo "max_input_vars=10000" > /usr/local/etc/php/conf.d/max_input_vars.ini && \
    rm -rf \
        /tmp/* \
        /var/tmp/* \
        /var/cache/apk/* \
        /etc/apk/cache/* \
        /root/.cache \
        /root/.composer/cache \
        /usr/local/lib/php/doc/* \
        /usr/local/lib/php/build \
        /usr/local/lib/php/test \
        /usr/local/lib/php/extensions/*/sodium.so \
        /usr/src/* \
        /usr/local/lib/libtommath.a \
        /usr/local/lib/libtomcrypt.a \
        /usr/local/bin/install-php-extensions

WORKDIR /var/www

COPY --chmod=0755 docker-entrypoint /usr/bin/

ENTRYPOINT ["docker-entrypoint"]
