FROM php:7.4-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
ADD --chmod=0755 https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

RUN apk add --no-cache openrc && \
    mkdir -p /run/openrc && \
    touch /run/openrc/softlevel && \
    sed -i 's/^#rc_sys=".*"/rc_sys="docker"/' /etc/rc.conf || true && \
    install-php-extensions bcmath gd mysqli pdo_mysql opcache pcntl redis swoole yaml zip && \
    echo "upload_max_filesize=1024M" > /usr/local/etc/php/conf.d/uploads.ini && \
    echo "post_max_size=1024M" > /usr/local/etc/php/conf.d/post.ini && \
    echo "memory_limit=512M" > /usr/local/etc/php/conf.d/memory.ini && \
    echo "max_execution_time=1200" > /usr/local/etc/php/conf.d/max_execution_time.ini && \
    echo "max_input_time=600" > /usr/local/etc/php/conf.d/max_input_time.ini && \
    echo "max_input_vars=10000" > /usr/local/etc/php/conf.d/max_input_vars.ini && \
    rm -rf \
        /tmp/* \
        /var/tmp/* \
        /var/cache/apk/* \
        /etc/apk/cache/* \
        /root/.cache \
        /root/.composer/cache \
        /usr/local/lib/php/doc/* \
        /usr/local/lib/php/build \
        /usr/local/lib/php/test \
        /usr/src/* \
        /usr/local/lib/libtommath.a \
        /usr/local/lib/libtomcrypt.a \
        /usr/local/bin/install-php-extensions

WORKDIR /var/www

COPY --chmod=0755 docker-entrypoint /usr/bin/

ENTRYPOINT ["docker-entrypoint"]
